name: Run DEXBot every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run worker
        run: |
          python run_worker.py

      - name: Commit updated memory/state/results
        run: |
          git config --global user.name "dexbot"
          git config --global user.email "bot@dex.ai"
          git add data || true
          git status
          git commit -m "Auto update results [bot]" || echo "Brak zmian do commita"
          # 🛡️ Ustawiamy URL z tokenem, żeby mieć prawo do push
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}