name: Run DEXBot every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Co 5 minut
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ⬅️ Kluczowe dla rebase

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot worker
        run: python run_worker.py

      - name: Commit and push results
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Commit and push results
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "dexbot"
          git config --global user.email "bot@dex.ai"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git pull origin main --rebase || echo "Nothing to rebase"
          git add data || true
          git commit -m "Auto update results [bot]" || echo "Brak zmian do commita"
          git push origin main || echo "Push failed"